# Generated by Django 4.2.5 on 2023-09-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_registrar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registrar',
        ),
    ]
