# Generated by Django 4.2.5 on 2023-09-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_student_registrar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='ID',
        ),
    ]
