# Generated by Django 4.2.5 on 2023-09-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_doc', models.CharField(max_length=200)),
                ('quota', models.IntegerField()),
            ],
        ),
    ]
