# Generated by Django 4.2.5 on 2023-09-29 20:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_courseenrollment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseEnrollment',
            new_name='Enroll',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
    ]
