# Generated by Django 4.2.5 on 2023-10-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_courseenrollment_enroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled',
            field=models.IntegerField(default=0),
        ),
    ]
